### ISSUE TITLE
Feature request - Filtro de azules

### ISSUE THREAD

**Issue by jorrgeCruz** [jorrgeCruz/image-processing#4]
Crear la característica para mostrar la imagen solo el canal de color azul, en el menu de Op. Basicas

**Comment by ReneNunez141023** [comment]
Buenas noches profe, disculpe la molesta, hoy no pude entrar a su clase ya que tuve un problema un tanto delicado y tuve que salir desde temprano, también no le entendí mucho a lo del filtro azul, el martes que viene si entro y ya me pondré al corriente, buena noche y una vez más disculpe profe

Enviado desde mi iPhone
